(function(){var EX=[
{title:"1 · Compra — Secuencial",problem:"Pide precio unitario y cantidad. Calcula y muestra el subtotal.",chips:["Definir","Leer","Escribir","<-"],starter:"Proceso Compra\n    Definir cantidad Como Entero\n    Definir precio, subtotal Como Real\n\n    // Completa aquí\n\nFinProceso",hint:"Lee precio y cantidad. Luego subtotal <- precio * cantidad. Finalmente escribe subtotal.",tests:[{i:["2500","4"],yes:["10000"]},{i:["1200","5"],yes:["6000"]}],solution:"Proceso Compra\n    Definir cantidad Como Entero\n    Definir precio, subtotal Como Real\n    Leer precio\n    Leer cantidad\n    subtotal <- precio * cantidad\n    Escribir \"Subtotal: \", subtotal\nFinProceso"},
{title:"2 · Temperatura — Condicional simple",problem:"Lee la temperatura. Si supera 8 °C, muestra “Revisar refrigeración”.",chips:["Si","Entonces","FinSi",">"],starter:"Proceso ControlTemperatura\n    Definir temperatura Como Real\n\n    // Completa aquí\n\nFinProceso",hint:"“Supera 8” significa temperatura > 8.",tests:[{i:["7"],no:["Revisar refrigeración"]},{i:["8"],no:["Revisar refrigeración"]},{i:["9"],yes:["Revisar refrigeración"]}],solution:"Proceso ControlTemperatura\n    Definir temperatura Como Real\n    Leer temperatura\n    Si temperatura > 8 Entonces\n        Escribir \"Revisar refrigeración\"\n    FinSi\nFinProceso"},
{title:"3 · Edad — Condicional doble",problem:"Si tiene 18 años o más, muestra “Puede ingresar”; si no, “No puede ingresar”.",chips:["Si","SiNo","FinSi",">="],starter:"Proceso ControlIngreso\n    Definir edad Como Entero\n\n    // Completa aquí\n\nFinProceso",hint:"Necesitas dos caminos. Usa SiNo.",tests:[{i:["17"],yes:["No puede ingresar"]},{i:["18"],yes:["Puede ingresar"]},{i:["25"],yes:["Puede ingresar"]}],solution:"Proceso ControlIngreso\n    Definir edad Como Entero\n    Leer edad\n    Si edad >= 18 Entonces\n        Escribir \"Puede ingresar\"\n    SiNo\n        Escribir \"No puede ingresar\"\n    FinSi\nFinProceso"},
{title:"4 · Acceso — Condición compuesta",problem:"Para ingresar debe tener 18 años o más Y presentar identificación.",chips:["Y","Logico","Verdadero","Falso"],starter:"Proceso AccesoActividad\n    Definir edad Como Entero\n    Definir tieneIdentificacion Como Logico\n\n    // Completa aquí\n\nFinProceso",hint:"La condición debe ser edad >= 18 Y tieneIdentificacion.",tests:[{i:["20","Verdadero"],yes:["Ingreso permitido"]},{i:["20","Falso"],yes:["Ingreso no permitido"]},{i:["17","Verdadero"],yes:["Ingreso no permitido"]}],solution:"Proceso AccesoActividad\n    Definir edad Como Entero\n    Definir tieneIdentificacion Como Logico\n    Leer edad\n    Leer tieneIdentificacion\n    Si edad >= 18 Y tieneIdentificacion Entonces\n        Escribir \"Ingreso permitido\"\n    SiNo\n        Escribir \"Ingreso no permitido\"\n    FinSi\nFinProceso"},
{title:"5 · Paquete — Validación + decisión",problem:"Peso ≤ 0 es inválido. Hasta 20 kg puede ir en moto; más de 20 kg requiere otro transporte.",chips:["Validación","Si anidado","<="],starter:"Proceso TransportePaquete\n    Definir peso Como Real\n\n    // Completa aquí\n\nFinProceso",hint:"Primero valida peso <= 0. En el SiNo, evalúa peso <= 20.",tests:[{i:["-2"],yes:["Peso inválido"]},{i:["0"],yes:["Peso inválido"]},{i:["15"],yes:["Puede ir en moto"]},{i:["20"],yes:["Puede ir en moto"]},{i:["21"],yes:["Requiere otro transporte"]}],solution:"Proceso TransportePaquete\n    Definir peso Como Real\n    Leer peso\n    Si peso <= 0 Entonces\n        Escribir \"Peso inválido\"\n    SiNo\n        Si peso <= 20 Entonces\n            Escribir \"Puede ir en moto\"\n        SiNo\n            Escribir \"Requiere otro transporte\"\n        FinSi\n    FinSi\nFinProceso"}];
function g(id){return document.getElementById(id)}var cur=0;
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function list(){g("exerciseList").innerHTML=EX.map(function(e,i){return '<button class="exercise '+(i===cur?'active':'')+'" data-i="'+i+'"><b>'+esc(e.title)+'</b><span>'+esc(e.chips.join(" · "))+'</span></button>'}).join("");document.querySelectorAll(".exercise").forEach(function(b){b.addEventListener("click",function(){load(Number(b.dataset.i))})})}
function load(i){cur=i;var e=EX[i];list();g("title").textContent=e.title;g("problem").textContent=e.problem;g("chips").innerHTML=e.chips.map(function(x){return '<span class="chip">'+esc(x)+'</span>'}).join("");g("code").value=e.starter;g("inputs").value="";g("console").textContent="Listo para ejecutar.";g("status").className="status";g("status").textContent="Escribe tu algoritmo y ejecútalo.";g("tests").innerHTML='<div class="test">Aún no has ejecutado las pruebas.</div>';g("solutionCode").textContent=e.solution;g("solutionCode").className="hidden"}
function val(v){var s=String(v).trim();if(/^verdadero$/i.test(s))return true;if(/^falso$/i.test(s))return false;if(/^[-+]?\d+(\.\d+)?$/.test(s))return Number(s);return s}
function expr(x,v){x=x.trim().replace(/<>/g,"!=").replace(/(^|[^<>=!])=([^=])/g,"$1==$2").replace(/\bY\b/gi,"&&").replace(/\bO\b/gi,"||").replace(/\bNO\b/gi,"!").replace(/\bVerdadero\b/gi,"true").replace(/\bFalso\b/gi,"false");Object.keys(v).sort(function(a,b){return b.length-a.length}).forEach(function(k){x=x.replace(new RegExp("\\b"+k+"\\b","g"),JSON.stringify(v[k]))});if(!/^[\s\d."'()+\-*\/%<>=!&|truefals]+$/i.test(x))throw Error("Expresión no reconocida: "+x);return Function('"use strict";return ('+x+')')()}
function write(t,v){var p=[],c="",q=false;for(var i=0;i<t.length;i++){var ch=t[i];if(ch==='"')q=!q;if(ch===","&&!q){p.push(c);c=""}else c+=ch}p.push(c);return p.map(function(z){z=z.trim();if(/^".*"$/.test(z))return z.slice(1,-1);if(Object.prototype.hasOwnProperty.call(v,z))return String(v[z]);try{return String(expr(z,v))}catch(e){return z}}).join("")}
function exec(code,inputs){var lines=code.replace(/\r/g,"").replace(/\/\/.*$/gm,"").split("\n").map(function(x){return x.trim()}).filter(Boolean),v={},out=[],inp=0;
function block(a,b){var i=a;while(i<b){var l=lines[i],m;if(/^(Proceso|FinProceso)\b/i.test(l)){i++;continue}m=l.match(/^Definir\s+(.+?)\s+Como\s+(\w+)/i);if(m){m[1].split(",").forEach(function(n){n=n.trim();v[n]=/logico/i.test(m[2])?false:/cadena/i.test(m[2])?"":0});i++;continue}m=l.match(/^Escribir\s+(.+)/i);if(m){out.push(write(m[1],v));i++;continue}m=l.match(/^Leer\s+([A-Za-z_]\w*)/i);if(m){if(inp>=inputs.length)throw Error("Falta un dato para Leer "+m[1]);v[m[1]]=val(inputs[inp++]);i++;continue}m=l.match(/^([A-Za-z_]\w*)\s*<-\s*(.+)$/);if(m){v[m[1]]=expr(m[2],v);i++;continue}m=l.match(/^Si\s+(.+?)\s+Entonces$/i);if(m){var d=1,j=i+1,e=-1;for(;j<b;j++){if(/^Si\s+.+\s+Entonces$/i.test(lines[j]))d++;else if(/^FinSi$/i.test(lines[j])){d--;if(d===0)break}else if(/^SiNo$/i.test(lines[j])&&d===1)e=j}if(d!==0)throw Error("Falta FinSi");if(Boolean(expr(m[1],v)))block(i+1,e>=0?e:j);else if(e>=0)block(e+1,j);i=j+1;continue}if(/^SiNo$|^FinSi$/i.test(l)){i++;continue}throw Error("No reconozco: "+l)}}block(0,lines.length);return out.join("\n")}
function run(){try{var a=g("inputs").value.split(",").map(function(x){return x.trim()}).filter(Boolean),o=exec(g("code").value,a);g("console").textContent=o||"(Terminó sin salida)";g("status").className="status ok";g("status").textContent="Ejecución completada."}catch(e){g("console").textContent="ERROR: "+e.message;g("status").className="status bad";g("status").textContent="Corrige el error indicado en consola."}}
function test(){var e=EX[cur],r=e.tests.map(function(t,n){try{var o=exec(g("code").value,t.i),ok=true;(t.yes||[]).forEach(function(s){if(o.toLowerCase().indexOf(s.toLowerCase())<0)ok=false});(t.no||[]).forEach(function(s){if(o.toLowerCase().indexOf(s.toLowerCase())>=0)ok=false});return {ok:ok,text:"Caso "+(n+1)+" · "+t.i.join(", ")+" → "+(o||"(sin salida)")}}catch(er){return {ok:false,text:"Caso "+(n+1)+" · Error: "+er.message}}});g("tests").innerHTML=r.map(function(x){return '<div class="test '+(x.ok?'ok':'bad')+'">'+(x.ok?'✅':'❌')+" "+esc(x.text)+"</div>"}).join("");var p=r.filter(function(x){return x.ok}).length;g("status").className="status "+(p===r.length?"ok":"bad");g("status").textContent="Pruebas superadas: "+p+"/"+r.length}
g("run").addEventListener("click",run);g("test").addEventListener("click",test);g("reset").addEventListener("click",function(){load(cur)});g("hint").addEventListener("click",function(){alert(EX[cur].hint)});g("solution").addEventListener("click",function(){g("solutionCode").classList.toggle("hidden")});g("code").addEventListener("keydown",function(e){if(e.key==="Tab"){e.preventDefault();var t=e.target,s=t.selectionStart,n=t.selectionEnd;t.value=t.value.slice(0,s)+"    "+t.value.slice(n);t.selectionStart=t.selectionEnd=s+4}});load(0)})();